# Generated by Django 4.1.7 on 2023-03-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NHL_Database', '0002_teamstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamStats',
            new_name='Teamtats',
        ),
    ]
