# Generated by Django 4.1.7 on 2023-03-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NHL_Database', '0003_rename_teamstats_teamtats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teamtats',
            new_name='Teamstats',
        ),
    ]
