# Generated by Django 4.1.7 on 2023-03-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NHL_Database', '0004_rename_teamtats_teamstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasons',
            name='season',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NHL_Database.seasons', to_field='season'),
        ),
    ]
