# Generated by Django 4.1.7 on 2023-03-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NHL_Database', '0006_rename_season_id_teamstats_season_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teamstats',
        ),
    ]
