# Generated by Django 4.1.7 on 2023-03-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NHL_Database', '0007_delete_teamstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamesPlayed', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('ptPctg', models.FloatField()),
                ('goalsPerGame', models.FloatField()),
                ('goalsAgainstPerGame', models.FloatField()),
                ('evGGARatio', models.FloatField()),
                ('powerPlayPercentage', models.FloatField()),
                ('powerPlayGoals', models.IntegerField()),
                ('powerPlayGoalsAgainst', models.IntegerField()),
                ('powerPlayOpportunities', models.IntegerField()),
                ('penaltyKillPercentage', models.FloatField()),
                ('shotsPerGame', models.FloatField()),
                ('shotsAllowed', models.FloatField()),
                ('winScoreFirst', models.FloatField()),
                ('winOppScoreFirst', models.FloatField()),
                ('winLeadFirstPer', models.FloatField()),
                ('winLeadSecondPer', models.FloatField()),
                ('winOutshootOpp', models.FloatField()),
                ('winOutshotByOpp', models.FloatField()),
                ('faceOffsTaken', models.IntegerField()),
                ('faceOffsWon', models.IntegerField()),
                ('faceOffsLost', models.IntegerField()),
                ('faceOffWinPercentage', models.FloatField()),
                ('shootingPctg', models.FloatField()),
                ('savePctg', models.FloatField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NHL_Database.seasons', to_field='season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NHL_Database.teams')),
            ],
        ),
    ]
