# Generated by Django 4.1.7 on 2023-03-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NHL_Database', '0008_teamstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryPosition', models.CharField(max_length=256)),
                ('nationality', models.CharField(max_length=256)),
                ('firstName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
            ],
        ),
    ]
