# Generated by Django 4.1.7 on 2023-03-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NHL_Database', '0011_alter_skaterseasonstats_assists_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.DeleteModel(
            name='SkaterSeasonStats',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='season',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='team',
        ),
        migrations.DeleteModel(
            name='Seasons',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
        migrations.DeleteModel(
            name='Teamstats',
        ),
    ]
