# Generated by Django 4.1.7 on 2023-03-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NHL_Database', '0014_tablestate_remove_skaterseasonstats_player_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablestate',
            old_name='table_name',
            new_name='model_name',
        ),
    ]
