# Generated by Django 4.1.7 on 2023-03-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NHL_Database', '0015_rename_table_name_tablestate_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablestate',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
